# Generated by Django 2.2.10 on 2020-03-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_number', models.CharField(help_text='20个字符以内', max_length=20, primary_key=True, serialize=False, verbose_name='飞机编号')),
                ('aircraft_type', models.CharField(choices=[('FW', '固定翼'), ('MR', '多旋翼'), ('HE', '直升机')], max_length=2, verbose_name='类型')),
                ('production_date', models.DateField(verbose_name='制造日期')),
                ('init_flight_hour', models.DecimalField(decimal_places=2, help_text='精度为0.01h', max_digits=7, verbose_name='飞行小时数初值')),
            ],
            options={
                'verbose_name': '飞行器',
                'verbose_name_plural': '飞行器',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('employee_id', models.CharField(help_text='4位数字', max_length=4, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(max_length=20, verbose_name='职务名称')),
                ('sex', models.CharField(choices=[('F', '男性'), ('M', '女性')], max_length=1)),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('joined_day', models.DateField(verbose_name='入职日期')),
            ],
            options={
                'verbose_name': '人员',
                'verbose_name_plural': '人员',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='20字以内', max_length=20, verbose_name='职务名称')),
                ('description', models.CharField(help_text='200字以内', max_length=200, verbose_name='职务描述')),
            ],
            options={
                'verbose_name': '职务',
                'verbose_name_plural': '职务',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_data', models.DateTimeField(verbose_name='任务日期')),
                ('place', models.CharField(max_length=50, verbose_name='任务地点')),
                ('mission_type', models.CharField(choices=[('1', '常规作业'), ('2', '维护'), ('3', '试验'), ('4', '其他')], max_length=1, verbose_name='任务类型')),
                ('duration', models.DecimalField(decimal_places=2, help_text='单位：h，精度：0.01', max_digits=7, verbose_name='飞行时间')),
                ('weather_type', models.CharField(choices=[('1', '晴朗'), ('2', '多云'), ('3', '阴'), ('4', '雨天'), ('5', '雪天'), ('6', '其他')], max_length=1, verbose_name='天气类型')),
                ('weather_description', models.CharField(help_text='100字以内', max_length=100, verbose_name='天气描述')),
                ('mission_description', models.CharField(help_text='300字以内', max_length=300, verbose_name='任务描述')),
                ('mission_situation', models.CharField(help_text='1000字以内', max_length=1000, verbose_name='任务实际状况')),
                ('other_people', models.CharField(help_text='100字以内', max_length=100, verbose_name='其他人员')),
                ('data_number', models.CharField(help_text='由12个数字组成，例如：201605120056', max_length=12, verbose_name='数据文件的编号')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flightmission.Aircraft')),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flightmission.Crew')),
                ('gcs_operator', models.ManyToManyField(related_name='mission_gcs_op', to='flightmission.Crew')),
                ('groundservice', models.ManyToManyField(related_name='mission_gservice', to='flightmission.Crew')),
                ('maintenance', models.ManyToManyField(related_name='mission_mai', to='flightmission.Crew')),
                ('pilot', models.ManyToManyField(related_name='mission_pilot', to='flightmission.Crew')),
                ('recorder', models.ManyToManyField(related_name='mission_rec', to='flightmission.Crew')),
                ('security', models.ManyToManyField(related_name='mission_sec', to='flightmission.Crew')),
            ],
            options={
                'verbose_name': '飞行任务',
                'verbose_name_plural': '飞行任务',
            },
        ),
        migrations.AddField(
            model_name='crew',
            name='duty',
            field=models.ManyToManyField(to='flightmission.Duty'),
        ),
    ]
