# Generated by Django 2.2.10 on 2020-03-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='description',
            field=models.CharField(blank=True, help_text='200字以内', max_length=200, verbose_name='职务描述'),
        ),
    ]
