# Generated by Django 2.2.10 on 2020-03-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightmission', '0002_auto_20200301_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_data',
            new_name='mission_date',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='data_number',
        ),
        migrations.AddField(
            model_name='mission',
            name='data_file',
            field=models.FileField(default='0', help_text='上传飞行数据文件', upload_to='mission-data-files', verbose_name='飞行数据文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crew',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
    ]
